# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitNanny < Formula
  desc "Cleans up dead local git branches: merged, squash-merged and forgotten"
  homepage "https://github.com/art-ps/git-nanny"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.1.1/git-nanny_0.1.1_darwin_x86_64.tar.gz"
      sha256 "3761f1eaa31b6e6b7d5aca755d618f631b329728eb492ef76c0fb193c5af0f44"

      define_method(:install) do
        bin.install "git-nanny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.1.1/git-nanny_0.1.1_darwin_arm64.tar.gz"
      sha256 "4ac43619187b7bf3138e079ccb66c19b53acf4a513b5e5d330c61b70fd8cff87"

      define_method(:install) do
        bin.install "git-nanny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.1.1/git-nanny_0.1.1_linux_x86_64.tar.gz"
      sha256 "f8f4dfe7c2cfc692673883cb1e8cff4b25639de7c3b31406d86e4a89ea1f34b5"
      define_method(:install) do
        bin.install "git-nanny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.1.1/git-nanny_0.1.1_linux_arm64.tar.gz"
      sha256 "9728e8e369f855b7ff6c9285e10cf66f2ff98bf952ce3a47daa5ab268f40bedb"
      define_method(:install) do
        bin.install "git-nanny"
      end
    end
  end

  test do
    system "git", "init", "-q", "-b", "main", testpath
    system "git", "-C", testpath, "commit", "-q", "--allow-empty", "-m", "init"
    assert_match "убирать нечего", shell_output("cd #{testpath} && #{bin}/git-nanny --dry-run")
  end
end
