# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitNanny < Formula
  desc "Cleans up dead local git branches: merged, squash-merged and forgotten"
  homepage "https://github.com/art-ps/git-nanny"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.3.0/git-nanny_0.3.0_darwin_x86_64.tar.gz"
      sha256 "54bc97fa671727d197b6908298715ac518555341c59c56ce13038ea30f132d73"

      define_method(:install) do
        bin.install "git-nanny"
        man1.install "man/git-nanny.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.3.0/git-nanny_0.3.0_darwin_arm64.tar.gz"
      sha256 "3666ce9d7bc809d6303292ee8297de37673d369bb9d562922bef4acbf858b520"

      define_method(:install) do
        bin.install "git-nanny"
        man1.install "man/git-nanny.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.3.0/git-nanny_0.3.0_linux_x86_64.tar.gz"
      sha256 "6b30017a25438e2c20255e7f0ba86aa0918d7c616cf72090a114c7f6fea5557f"
      define_method(:install) do
        bin.install "git-nanny"
        man1.install "man/git-nanny.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.3.0/git-nanny_0.3.0_linux_arm64.tar.gz"
      sha256 "d9ae67af79c7c0350f1712a4a9419d236b96b7906e10b972ebcda82c274184f6"
      define_method(:install) do
        bin.install "git-nanny"
        man1.install "man/git-nanny.1"
      end
    end
  end

  test do
    system "git", "init", "-q", "-b", "main", testpath
    system "git", "-C", testpath, "commit", "-q", "--allow-empty", "-m", "init"
    assert_match "nothing to clean", shell_output("cd #{testpath} && #{bin}/git-nanny --dry-run")
  end
end
