# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitNanny < Formula
  desc "Cleans up dead local git branches: merged, squash-merged and forgotten"
  homepage "https://github.com/art-ps/git-nanny"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.2.0/git-nanny_0.2.0_darwin_x86_64.tar.gz"
      sha256 "c227252a3ba0a4fe915aa490a7d0f1b996c0f82f3aae8a64487351d2e795b7d0"

      define_method(:install) do
        bin.install "git-nanny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.2.0/git-nanny_0.2.0_darwin_arm64.tar.gz"
      sha256 "925a0ba6d4d7f8971672fb8d63c694e54f17c14c4c055db7cb56a27ee597a731"

      define_method(:install) do
        bin.install "git-nanny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.2.0/git-nanny_0.2.0_linux_x86_64.tar.gz"
      sha256 "abc86c9be87fc52fc32dea96e2ac33ca1fcae70542dd51fc52c0550e5dfba95a"
      define_method(:install) do
        bin.install "git-nanny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/git-nanny/releases/download/v0.2.0/git-nanny_0.2.0_linux_arm64.tar.gz"
      sha256 "9391115eb2875abdc5d5027853ab88d56f98d33ae00fbf583f0b5cf95423b3f0"
      define_method(:install) do
        bin.install "git-nanny"
      end
    end
  end

  test do
    system "git", "init", "-q", "-b", "main", testpath
    system "git", "-C", testpath, "commit", "-q", "--allow-empty", "-m", "init"
    assert_match "nothing to clean", shell_output("cd #{testpath} && #{bin}/git-nanny --dry-run")
  end
end
