# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sftpcommander < Formula
  desc "Terminal SFTP client with a keyboard-driven TUI"
  homepage "https://github.com/art-ps/sftpcommander"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.2/sftpcommander_0.1.2_darwin_x86_64.tar.gz"
      sha256 "e30707bdab0444322aedbe4a9e2a6db7ff0d3b8beae84e035165bf7fec002a2b"

      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.2/sftpcommander_0.1.2_darwin_arm64.tar.gz"
      sha256 "0716eab5d5d8d077278aadfd521280f95c76fc14d78a87f582f590f82558ffa0"

      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.2/sftpcommander_0.1.2_linux_x86_64.tar.gz"
      sha256 "f2aa4d64601624fecdb3388be5958efa7eed29a51c14b18e64d0221998b63d5f"
      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.2/sftpcommander_0.1.2_linux_arm64.tar.gz"
      sha256 "9239b0f95ff23259a06b59af6bff1e3036f8a28689dcbd5fa9b92baf1b27762d"
      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
  end
end
