# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sftpcommander < Formula
  desc "Terminal SFTP client with a keyboard-driven TUI"
  homepage "https://github.com/art-ps/sftpcommander"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.0/sftpcommander_0.1.0_darwin_x86_64.tar.gz"
      sha256 "4d01a523d5a0f12865557a277e1b05d22597f060dc5aa10b0eeec5b4de125888"

      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.0/sftpcommander_0.1.0_darwin_arm64.tar.gz"
      sha256 "5c20fe0515ebbb93bf9d5a3c4170de9c8f57de9068acb0a88927d1ce186296df"

      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.0/sftpcommander_0.1.0_linux_x86_64.tar.gz"
      sha256 "8729bca1a9a79fe4fbba2c96d1ee2d59123908c74b7ad4c928c408beee5c4ecf"
      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/art-ps/sftpcommander/releases/download/v0.1.0/sftpcommander_0.1.0_linux_arm64.tar.gz"
      sha256 "104566139f86035db774feb21f8ecaa9a4ea0df93b3726b3cd20d671cae0373d"
      define_method(:install) do
        bin.install "sftpcommander"
      end
    end
  end
end
